language: objective-c
osx_image: xcode11.3
before_install:
- brew install gnu-sed
- export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
- export LC_ALL=en_US.UTF-8
- git config --global user.email "maxime.colmant@gmail.com"
- git config --global user.name "Maxime Colmant"
- gem install cocoapods xcpretty --no-document --quiet
script:
- ./ci/build-cocoapods.sh
- |
  if ! [ -z "$TRAVIS_TAG" ]; then
    ./ci/publish-cocoapods.sh --tag="${TRAVIS_TAG}" &&
    git add IndoorLocation.podspec &&
    { git diff-index --quiet HEAD IndoorLocation.podspec || git commit -m ":robot: chore: updating the Podspec's version to ${TRAVIS_TAG} :robot:"; } &&
    git switch -c master &&
    git push -q https://${GITHUB_TOKEN}@github.com/IndoorLocation/indoor-location-ios.git master
  fi;
